{% set name = "redbird" %}
{% set version = "0.7.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/redbird-{{ version }}.tar.gz
  sha256: 9ef1098f2a0e68afe40349475018f7694b05bdf92250772cd8d0126f26de58a9

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - pydantic
    - python >={{ python_min }}
    - typing-extensions

test:
  imports:
    - redbird
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/Miksus/red-bird
  doc_url: https://red-bird.readthedocs.io/
  summary: Repository Patterns for Python
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
